"""Directory_Caching's setup.py.

This file was autogenerated by pypackage. To make changes, you
should edit the pypackage.meta rather than this setup.py.
"""


try:
    from setuptools import setup, find_packages
except:
    from disutils.core import setup, find_packages

__title__ = 'directory_caching'
__module_name__ = __title__
__version__ = '1.12'
__author__ = 'Benjamin Schollnick'
__author_email__ = 'Benjamin@schollnick.net'
__license__ = 'MIT'
__copyright__ = 'Copyright 2015 Benjamin Schollnick'
__github_url__ = 'https://github.com/bschollnick/Directory_Caching/tree/master'
#__github_dl_url__ = 'https://github.com/bschollnick/Directory_Caching/archive/v1.05.zip'

__pypi_keywords__ ='caching files directories scandir naturalsort'


dependencies = ['natsort', 'scandir']

setup(
    name=__title__,
    version=__version__,
    description='Simple and basic Directory Listing, File information, & Zip File Listings Caching.',
    author=__author__,
    author_email=__author_email__,
    maintainer=__author__,
    maintainer_email=__author_email__,
    url=__github_url__,
    download_url=__github_url__,
    py_modules=[__module_name__],
    classifiers=[
        'Development Status :: 5 - Production/Stable',
        'Intended Audience :: Developers',
        'Operating System :: MacOS :: MacOS X',
        'Operating System :: Microsoft :: Windows :: Windows 7',
        'Operating System :: Microsoft :: Windows :: Windows XP',
        'Operating System :: POSIX :: Linux',
        'Programming Language :: Python :: 2'
    ],
    include_package_data=True,
    package_data={
        'Docs': 'docs/*',
        'tools': 'tools/*'
    },
    packages=['directory_caching'],
    requires=dependencies,
    long_description='Simple and basic Directory Listing &amp; File information  Caching.',
    keywords = __pypi_keywords__

)
